### ISSUE TITLE
Add command to mark commands ass completed

### ISSUE THREAD

**Issue by nowakjestem** [daverdalas/laravel-post-deploy-commands#1]
Sometimes you need to run deplaoy commands on your local enviroment, but commands may use data/code which doesn't exists on current version of app, and running them causes error (eg. table not found :grinning:). 
I think good solution to this will be adding a command to mark all/some tests as done, somthing like
`php artisan deploy-commands:mark-completed [--name]`

**Comment by daverdalas** [comment]
Added command: `php artisan deploy-commands:mark-all-completed`. Thanks for support :)
